[package]
name = "render"
version = "0.1.0"
authors = ["Matthias Endler <matthias-endler@gmx.net>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0.39"
serde_yaml = "0.7"
tera = "0.11.6"
quicli = "0.2"
lazy_static = "1.0.0"
url = "1.7.0"
url_serde = "0.2.0"
